# Mqtt配置
mqtt:
  serverURIs: tcp://127.0.0.1:1883,tcp://192.168.91.100:1883  #服务器url
  username: cym   #用户名
  password: 123 #密码
  topic: topic_default
  qos: 1  #通信质量
  client:
    id: mqttx_400702eb

spring:
  application:
    name: MQTT-DEMO



