# Mqtt配置
mqtt:
  serverURIs: tcp://127.0.0.1:1883  #服务器url
  username: cym   #用户名
  password: 123 #密码
  cleanSession: true #是否清除会话
  reconnect: true #是否断线重连
  timeout: 20 #连接超时时间
  keepAlive: 10 #心跳间隔
  topic: topic_default
  qos: 0  #通信质量
  client:
    id: mqttx_400702

spring:
  application:
    name: MQTT-DEMO



